import { readFileSync } from 'node:fs';
import { join } from 'node:path';

/**
 * Intrinsic dimensions for the images under public/static, so components can
 * emit width/height and let the browser reserve the right box before the image
 * arrives (avoids layout shift, which Core Web Vitals measures as CLS).
 *
 * Backed by src/content/image-dimensions.json, generated by
 * `pnpm images:manifest`. Regenerate after adding or replacing an image.
 */

export interface Dimensions {
  width: number;
  height: number;
}

/** Largest responsive derivative we generate; no point advertising more. */
const MAX_WIDTH = 1440;

let _cache: Record<string, Dimensions> | null = null;

function loadManifest(): Record<string, Dimensions> {
  if (_cache) return _cache;
  const raw = readFileSync(join(process.cwd(), 'src/content/image-dimensions.json'), 'utf-8');
  _cache = JSON.parse(raw) as Record<string, Dimensions>;
  return _cache;
}

/**
 * Dimensions for a site-absolute image path, scaled down to MAX_WIDTH while
 * preserving the aspect ratio — the ratio is what prevents layout shift, and
 * advertising a 5184px width on a photo displayed at 400px is just noise.
 *
 * Returns null for unknown paths (SVGs, remote images) so callers can decide.
 */
export function getImageDimensions(src: string): Dimensions | null {
  const entry = loadManifest()[src];
  if (!entry) return null;

  if (entry.width <= MAX_WIDTH) return entry;

  const scale = MAX_WIDTH / entry.width;
  return {
    width: MAX_WIDTH,
    height: Math.round(entry.height * scale),
  };
}

/**
 * Spreadable width/height attributes for a plain `<img>`: `<img {...imgSize(src)} />`.
 * Yields nothing for unknown paths, so callers never emit half a pair.
 */
export function imgSize(src: string | undefined): Dimensions | Record<string, never> {
  return src ? (getImageDimensions(src) ?? {}) : {};
}
